# Deployment configurations  
stable:
  replicas: 2
  version: v1
  containerSpecImagePullPolicy: Always
  containerNameFrontend: case-study-canary-frontend
  containerNameBackend: case-study-canary-api
  imageFrontend: httpd
  imageBackend: httpd
  imageTagFrontend: latest
  imageTagBackend: latest
  resourcesFrontend:
    requestsMemory: 50Mi
    requestsCpu: 50m
    limitsMemory: 90Mi
    limitsCpu: 100m
  resourcesBackend:
    requestsMemory: 50Mi
    requestsCpu: 50m
    limitsMemory: 90Mi
    limitsCpu: 100m
  portFrontend: 80
  portBackend: 8080

# Canary roll out policy
canary:
  timeBeforeRollBack: 60
  servicePort: 80
  interval: 15s
  maxFailed: 5
  maxTraficRouted: 75
  stepWeight: 25
  minRequestsSuccessRate: 90
  cheakIntervall: 2m

# Specify ingress configuration for targets and path
ingress:
  target: /
  ingressPath: /
  pathType: ImplementationSpecific
  clasteIssuareName: "letsencrypt-prod"
  hostname: test.loc #casestudy.polandcentral.cloudapp.azure.com
  tlsSercret: secretname
clusterIssuer:
  email: vitalikstelmah60@gmail.com
  server: "https://acme-v02.api.letsencrypt.org/directory"
  privateKeySecretName: "letsencrypt-prod-key"
