apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-frontend
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: {{ .Release.Name }}-ingress
  progressDeadlineSeconds: {{ .Values.canary.timeBeforeRollBack }}
  service:
    port: {{ .Values.canary.servicePort }}
    targetPort: {{ .Values.stable.portFrontend }}
{{- with .Values.canary }}
  analysis:
    interval: {{ .interval }}
    threshold: {{ .maxFailed }}
    maxWeight: {{ .maxTraficRouted }}
    stepWeight: {{ .stepWeight }}
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: {{ .minRequestsSuccessRate }}
      interval: {{.cheakIntervall }}
{{- end }}