apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.stable.portBackend }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
    version: {{ .Values.stable.version }}
spec:
  replicas: {{ .Values.stable.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
    {{-  with .Values.stable }}
      containers:
      - name: {{ .containerNameBackend }}
        image: "{{ .imageBackend }}:{{ .imageTagBackend }}"
        imagePullPolicy: {{ .containerSpecImagePullPolicy }}
        resources:
          requests:
            memory: {{ .resourcesBackend.requestsMemory }}
            cpu: {{ .resourcesBackend.requestsCpu }}
          limits:
            memory: {{ .resourcesBackend.limitsMemory }}
            cpu: {{ .resourcesBackend.limitsCpu }}
        ports:
        - containerPort: {{ .portBackend }}
  {{- end }}